import esbuild from "esbuild";
import process from "process";
// 官方合规写法：使用原生 module 替代第三方的 builtin-modules
import { builtinModules } from "module";

const prod = (process.argv[2] === "production");

const context = await esbuild.context({
    banner: {
        js: '/*\nTHIS IS A GENERATED/BUNDLED FILE BY ESBUILD\n*/',
    },
    entryPoints: ["main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtinModules
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
});

if (prod) {
    await context.rebuild();
    process.exit(0);
} else {
    await context.watch();
}
